[package]
name = "xtask"
version = "1.0.0"
edition = "2021"

[dependencies]
# nih-plug conveniently provides the `bundle` xtask as a library.
nih_plug_xtask = { git = "https://github.com/robbert-vdh/nih-plug.git" }